# Generated by Django 5.2.1 on 2025-06-16 04:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SentencePack",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                (
                    "original_author",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("sentences", models.JSONField()),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sentences",
                        to="user.user",
                    ),
                ),
            ],
        ),
    ]
