# Generated by Django 5.2.1 on 2025-06-16 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sentence", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sentencepack",
            name="sentences",
            field=models.TextField(),
        ),
    ]
