# Generated by Django 5.2.1 on 2025-06-16 05:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sentence", "0002_alter_sentencepack_sentences"),
        ("user", "0002_rename_user_gameuser"),
    ]

    operations = [
        migrations.CreateModel(
            name="SentenceLeaderboard",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("total_score", models.IntegerField(default=0)),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="game_scores",
                        to="user.gameuser",
                    ),
                ),
                (
                    "sentence_pack",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leaderboards",
                        to="sentence.sentencepack",
                    ),
                ),
            ],
            options={
                "unique_together": {("sentence_pack", "player")},
            },
        ),
    ]
