# Generated by Django 5.2.1 on 2025-06-18 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sentence", "0003_sentenceleaderboard"),
    ]

    operations = [
        migrations.AddField(
            model_name="sentencepack",
            name="level",
            field=models.CharField(
                choices=[
                    ("A", "상"),
                    ("B", "중상"),
                    ("C", "중"),
                    ("D", "중하"),
                    ("E", "하"),
                ],
                default="C",
                max_length=1,
            ),
            preserve_default=False,
        ),
    ]
