# Generated by Django 5.2.1 on 2025-06-19 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sentence", "0004_sentencepack_level"),
    ]

    operations = [
        migrations.RenameField(
            model_name="sentenceleaderboard",
            old_name="total_score",
            new_name="score",
        ),
    ]
