# Generated by Django 5.2.1 on 2025-06-19 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sentence", "0004_sentencepack_level"),
    ]

    operations = [
        # field was already named 'score' in 0003, no-op for fresh installs
    ]
