# Generated by Django 5.2.1 on 2025-07-14 04:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sentence", "0004_sentencepack_level"),
        ("user", "0004_alter_gameuser_nickname"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="sentencepack",
            options={"verbose_name": "문장세트", "verbose_name_plural": "문장세트들"},
        ),
        migrations.CreateModel(
            name="SentencePackLike",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="좋아요 누른 시각"
                    ),
                ),
                (
                    "pack",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="likes",
                        to="sentence.sentencepack",
                        verbose_name="좋아요 받은 게시글",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="likes_given",
                        to="user.gameuser",
                        verbose_name="좋아요 누른 사용자",
                    ),
                ),
            ],
            options={
                "verbose_name": "좋아요",
                "verbose_name_plural": "좋아요들",
                "unique_together": {("user", "pack")},
            },
        ),
    ]
