# Generated by Django 5.2.1 on 2025-07-16 01:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sentence", "0005_alter_sentencepack_options_sentencepacklike"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="sentenceleaderboard",
            options={"verbose_name": "리더보드값", "verbose_name_plural": "리더보드"},
        ),
    ]
