# Generated by Django 5.2.1 on 2025-07-16 02:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sentence", "0006_alter_sentenceleaderboard_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="sentencepack",
            name="image_id",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="sentencepacklike",
            name="pack",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="likes",
                to="sentence.sentencepack",
                verbose_name="좋아요 받은 문장세트",
            ),
        ),
    ]
