# Generated by Django 5.2.1 on 2026-09-01 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sentence", "0006_alter_sentencepack_options_sentencepacklike"),
    ]

    operations = [
        migrations.AddField(
            model_name="sentencepack",
            name="image_url",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
