# Generated by Django 5.2.1 on 2025-07-16 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sentence", "0007_sentencepack_image_id_alter_sentencepacklike_pack"),
    ]

    operations = [
        migrations.AddField(
            model_name="sentencepack",
            name="image_file",
            field=models.ImageField(
                blank=True, null=True, upload_to="sentence_pack_images/"
            ),
        ),
        migrations.AlterField(
            model_name="sentencepack",
            name="image_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
