# Generated by Django 5.2.1 on 2025-07-16 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sentence", "0008_sentencepack_image_file_alter_sentencepack_image_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sentencepack",
            name="image_file",
        ),
        migrations.RemoveField(
            model_name="sentencepack",
            name="image_id",
        ),
        migrations.AddField(
            model_name="sentencepack",
            name="image_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
