# Generated by Django 5.2.1 on 2025-06-16 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sentence", "0001_initial"),
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="User",
            new_name="GameUser",
        ),
    ]
