# Generated by Django 5.2.1 on 2025-06-17 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_rename_user_gameuser"),
    ]

    operations = [
        migrations.AddField(
            model_name="gameuser",
            name="login_code",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
