# Generated by Django 5.2.1 on 2025-06-18 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0003_gameuser_login_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gameuser",
            name="nickname",
            field=models.CharField(max_length=150),
        ),
    ]
