# Generated by Django 5.2.1 on 2025-07-16 01:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0004_alter_gameuser_nickname"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="gameuser",
            options={"verbose_name": "유저", "verbose_name_plural": "유저"},
        ),
    ]
