# Generated by Django 5.2.1 on 2025-07-17 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0005_alter_gameuser_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="gameuser",
            name="history",
            field=models.TextField(blank=True, default="[]", null=True),
        ),
        migrations.AddField(
            model_name="gameuser",
            name="now",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
